TESTBENCH = top_tb
GHDL_SIM_OPT = --stop-time=100us
FILES = \
	../hdl/example4.vhd \
	../hdl/gpio.vhd \
	../hdl/bootrom.vhd \
	../lib/TG68/VHDL/TG68_fast.vhd \
	../lib/TG68/VHDL/TG68.vhd

include makefile.ghdl.mk
